GET http://localhost:3000/players

###


GET http://localhost:3000/tables

###

POST http://localhost:3000/scores
Content-Type: application/json

{
    "team": "Shetland",
    "score": 0
}

###

DELETE http://localhost:3000/tables/5e486f79b844051b88904d34

###

PATCH http://localhost:3000/tables/5e47e26af51127351cc19197
Content-Type: application/json

{
    "player2Name": "Fast Eddie"
}